### ISSUE TITLE
Wed not showing international characters on Ubuntu 18.04

### ISSUE THREAD

**Issue by kerberosdelhades** [rgburke/wed#9]
### Results in nano editor, less, more, cat, etc. for the string 'éêüñ':
>éêüñ
## Behavior for wed:
I can get accents and international characters (é, ê, ü, ñ) elsewhere on the terminal (xterm, mate-terminal, terminator). But when I try to open a file with international characters in wed, I get garbage with the editor. Same result if I try to write directly the international characters.
### Results in wed for the string 'éêüñ':
>M-CM-1M-CM-!scM-CM-<lM-CM-*
## Compilation options
The compilation options are as follows:
```
user@ahura:/opt/source/wed$ ./configure --prefix=/opt/usr --enable-lua --disable-gnu-source-highlight
```

## Additional details 
- As previously stated, I have international characters as usual in every application that runs on the terminal, except for wed. Codification is UTF-8. Changing it to ISO-8859-1 or ISO-8859-15 does not improve the situation.
- In the file explorer you get also garbage, plus unexpected indentation of the following filenames after a filename with international characters.
- Operating system: Ubuntu 18.04.2 LTS

**Comment by rgburke** [comment]
Thanks for trying wed and reporting this issue. I think that wed is linking against libncurses and that's why it's displaying UTF-8 characters incorrectly. In order to display UTF-8 characters correctly it will need to link against libncursesw.
If you run `ldd $(which wed) | grep ncurses` do you see libncurses.so.5? If so could you install ncurses with wide character support:
```
sudo apt install libncursesw5-dev
```
and then re-run the configure script and recompile wed to see if it then displays UTF-8 characters correctly?

**Comment by kerberosdelhades** [comment]
> user@ahura$ sudo apt remove libncurses5-dev 
> user@ahura$ sudo apt install libncursesw5-dev
> user@ahura$ ./configure --prefix=/opt/usr

That fixed the problem, thanks!
